import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import { Providers } from './providers'
import "./globals.css";

const archivo = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Madingku",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={archivo.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
